name: Build Wheels

on:
  push:
    branches:
      - main
    paths:
      - darshan-util/**
      - include/**
  pull_request:
    branches:
      - main
    paths:
      - darshan-util/**
      - include/*

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    if: >-
      contains(needs.get_commit_message.outputs.message, '[wheel build]') ||
      github.event_name == 'workflow_dispatch'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.5.0
        with:
          package-dir: ./darshan-util/pydarshan

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
